"""empty message

Revision ID: 0adc3b68c195
Revises: 
Create Date: 2025-12-09 12:47:37.264176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adc3b68c195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('temperature', 'pression', 'rythme', name='typecapteur'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personne',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('medecin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['personne.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['personne.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=False),
    sa.Column('date_heure_alerte', sa.DateTime(), nullable=True),
    sa.Column('niveau_urgence', sa.Enum('faible', 'moyenne', 'critique', name='urgenceenum'), nullable=False),
    sa.Column('type_alerte', sa.Enum('urgence', 'avertissement', 'information', name='typealerte'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('etat_traitement', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecin.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donnees_medicales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('capteur_id', sa.Integer(), nullable=False),
    sa.Column('valeur_mesuree', sa.Float(), nullable=False),
    sa.Column('date_heure_mesure', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capteur_id'], ['capteur.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lien_parente', sa.String(length=100), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['personne.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyseur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=False),
    sa.Column('donnee_medicale_id', sa.Integer(), nullable=False),
    sa.Column('resultat', sa.String(length=255), nullable=True),
    sa.Column('date_analyse', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donnee_medicale_id'], ['donnees_medicales.id'], ),
    sa.ForeignKeyConstraint(['medecin_id'], ['medecin.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyseur')
    op.drop_table('proche')
    op.drop_table('donnees_medicales')
    op.drop_table('alerte')
    op.drop_table('patient')
    op.drop_table('medecin')
    op.drop_table('personne')
    op.drop_table('capteur')
    # ### end Alembic commands ###
